// Generated by CoffeeScript 1.8.0
(function() {
  var gulp;

  gulp = require('gulp');

  gulp.task('express', function() {
    var app, express;
    express = require('express');
    app = express();
    app.use(express["static"]('.'));
    app.listen(9201);
  });

  gulp.task('default', ['express'], function() {});

}).call(this);

//# sourceMappingURL=Gulpfile.js.map
